account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('signup/', views.signUp_view, name="signup"),
    path('logout/', views.logout_view, name="logout")
]

daftarrumahsakit/urls.py
from django.urls import path
from . import views

app_name = 'daftarrumahsakit'

urlpatterns = [
    path('', views.home, name='home'),
    path('<single_slug>', views.single_slug, name='single_slug'),
    path('search/', views.search, name='search'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path('', views.index, name="index"),
    path('getposts', views.getPosts, name="getPosts"),
    path('view/<int:id>', views.view, name="view"),
    path('post/', views.post, name="post"),
    path('reply/<int:id>', views.reply, name="reply"),
    path('upvote/<int:id>', views.upvote, name="upvote"),
    path('downvote/<int:id>', views.downvote, name="downvote")
]

learningplaceApp/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from .views import index
from .views import testimonial_section
from .views import show_testimonial

app_name = "learningplace"

urlpatterns = [
    path("", index, name="index"),
	path('testimonial/', views.testimonial_section, name='testimonial'),
    path('testimonial/api/', views.show_testimonial, name='showtestimonial')
]

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, Subscribe, SaveSubscription, developer

app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path('subscribe/', Subscribe, name="subscribe"),
    path('subscribe/save/', SaveSubscription, name="save"),
    path('developer/', developer, name="developer")
]

newnormalinfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('rumahsakit/', include('daftarrumahsakit.urls')),
    path('tempatbelajar/', include('learningplaceApp.urls')),
    #path('testimonial/', include('testimonialbyuserApp.urls')),
    path('forum/', include('forum.urls')),
    path('account/', include('account.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> New Normal Info </title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

    <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

<!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" arel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Font -->
  <link href="https://fonts.googleapis.com/css2?family=Rowdies&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Smythe&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Sarabun&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Sanchez&display=swap" rel="stylesheet">
  <link href="https://fonts.cdnfonts.com/css/yaldevi-colombo" rel="stylesheet">

  <!-- Vendor CSS Files -->

<!-- Dev Page -->
  <!-- <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'> -->


  <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">



  <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/icofont/icofont.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/venobox/venobox.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/aos/aos.css' %}">

  <!-- Template Main CSS File -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

  
      
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="  https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

  <!-- <script src="{% static 'js/main.js' %}"></script> -->


  
  <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
<!-- JS Cookies -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js" integrity="sha512-Meww2sXqNHxI1+5Dyh/9KAtvI9RZSA4c1K2k5iL02oiPO/RH3Q30L3M1albtqMg50u4gRTYdV4EXOQqXEI336A==" crossorigin="anonymous"></script>

<!-- Developer Page -->

      <!-- CSS -->
      <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
      
      <!-- JQuery -->
      <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>


       <!-- JavaScript -->
      <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'></script>

     
      <!-- Icons -->
      <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>

<!-- Testimonial Page -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.js" integrity="sha512-JjYSgzqo9K0IeYGEslMRYE8aO9tq7Ky3EQNmEVkAe6Cp14AwlJMLMnb0fpgEkr3YxJ8ghQiriOvZwIdRZieGIQ==" crossorigin="anonymous"></script>

    {% block css %}
        <!-- <link rel="stylesheet" href="{% static 'style.css' %}" /> -->
    {% endblock %}

</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'main:index' %}"><span> New Normal Info </span></a></h1>
    
      </div>

      <nav class="nav-menu d-none d-lg-block">

        <ul>
          <li id="hum"><a href="{% url 'main:index' %}"> Home </a></li>
          <li><a href="{% url 'daftarrumahsakit:home' %}"> RS </a>
     

          <li><a href="{% url 'learningplace:index' %}"> Learning Place </a>
    


          <li id="port"><a href="{% url 'forum:index' %}"> Forum </a></li>
          <li id="price"><a href="{% url 'main:developer' %}"> Developer </a></li>

          {% if user.is_authenticated %}
          <li><a href="#"><span class="glyphicon glyphicon-user"></span>Halo {{ request.user.username }}</a></li>
          <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
          {% else %}
          <li><a href="{% url 'account:signup' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
          <li><a href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
          {% endif %}


        </ul>
      </nav>

    </div>
  </header>
  <!-- End Header -->

      {% block content %}
      {% endblock %}  
 
       <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3> New Normal Info </h3>
          
                
                <p> Fakultas Ilmu Komputer <br>
                Kampus UI Depok, Pondok Cina, <br>
                Kecamatan Beji, Kota Depok, <br>
                Jawa Barat 16424 <br> <br>
             
                <strong>Phone:</strong> 
              
                (021)881646712
                <br>
                <strong>Email:</strong> 
              
                 new-normal-info@cs.ui.ac.id <br>
              </p>

        </div>
      </div>
      
          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:index' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'daftarrumahsakit:home' %}">RS</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'learningplace:index' %}">Learning Place</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'forum:index' %}">Forum</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:developer' %}">Developer</a></li>
            </ul>
          </div>

 
          <div class="col-lg-3 col-md-6" id="quotesyuk">
            <div class="footer-info">
              <h3> Quotes </h3>
          <p> Either you run the day </p>
          <p> or the day runs you </p>



          </div>
        </div>



     


   <!-- Vendor JS Files -->
   <script src="{% static "assets/vendor/jquery/jquery.min.js" %}" ></script>
   <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
   <script src="{% static "assets/vendor/jquery.easing/jquery.easing.min.js" %}"></script>
   <script src="{% static "assets/vendor/php-email-form/validate.js" %}"></script>
   <script src="{% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
   <script src="{% static "assets/vendor/venobox/venobox.min.js" %}"></script>
   <script src="{% static "assets/vendor/owl.carousel/owl.carousel.min.js" %}"></script>
   <script src="{% static "assets/vendor/aos/aos.js" %}"></script>
 
   <!-- Template Main JS File -->
   <script src="{% static "js/main.js" %}"></script>
   
 

</body>
</html>

templates/contactusform.html
<!-- ======= Contact Us Section ======= -->
<section id="contact-form1" class="contact section-bg">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h2>Contact Us</h2>
      </div>

      <div class="row">

        <div class="col-lg-5 d-flex align-items-stretch" data-aos="fade-right">
          <div class="info">
            <div class="address">
              <i class="icofont-google-map"></i>
              <h4> Location: </h4>
              <p> Kampus UI Depok, Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424 </p>
            </div>

            <div class="email">
              <i class="icofont-envelope"></i>
              <h4>Email:</h4>
              <p>new-normal-info@cs.ui.ac.id</p>
            </div>

            <div class="phone">
              <i class="icofont-phone"></i>
              <h4> Call: </h4>
              <p> (021) 881646712 </p>
            </div>
            
          <!-- menampilkan maps dari Fasilkom UI using iFrame -->
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.228418144345!2d106.82648981402879!3d-6.364477795394506!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69ec1ad14fb6cf%3A0xc94e4d829420fa15!2sFakultas%20Ilmu%20Komputer%20Universitas%20Indonesia!5e0!3m2!1sid!2sid!4v1605468095965!5m2!1sid!2sid" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
         
          </div>
        </div>
        

        <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch" data-aos="fade-left">

             <div class="form-row">
              <div class="form-group col-md-6">
              <form method='POST' novalidate>
                        {% csrf_token %}
                    
                        {{ form.as_p }}
                    
                <div><input type='submit' value='Send Message' style='background-color: #4390BC !important; color: white;'/> </div>
          
              </form>
          </div>                          
          

        </div>
  

      </div>

    </div>
  </section><!-- End Contact Us Section -->

templates/dasar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> New Normal Info </title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

    <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

<!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" arel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Font -->
  <link href="https://fonts.googleapis.com/css2?family=Rowdies&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Smythe&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Sarabun&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Sanchez&display=swap" rel="stylesheet">
  <link href="https://fonts.cdnfonts.com/css/yaldevi-colombo" rel="stylesheet">

  <!-- Vendor CSS Files -->

<!-- Dev Page -->
  <!-- <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'> -->


  <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">



  <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/icofont/icofont.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/venobox/venobox.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/aos/aos.css' %}">

  <!-- Template Main CSS File -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

  
      
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="  https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

  <!-- <script src="{% static 'js/main.js' %}"></script> -->


  
  <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
 

<!-- Developer Page -->

      <!-- CSS -->
      <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
      
      <!-- JQuery -->
      <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>


       <!-- JavaScript -->
      <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'></script>

     
      <!-- Icons -->
      <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>

  
    {% block css %}
        <!-- <link rel="stylesheet" href="{% static 'style.css' %}" /> -->
    {% endblock %}
    
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex">

      <div class="logo mr-auto">
        <h1 class="text-light"><a href="{% url 'main:index' %}"><span> New Normal Info </span></a></h1>
    
      </div>

      <nav class="nav-menu d-none d-lg-block">

        <ul>
          <li id="hum"><a href="{% url 'main:index' %}"> Home </a></li>
          <li><a href="{% url 'daftarrumahsakit:home' %}"> RS </a>
     

          <li><a href="{% url 'learningplace:index' %}"> Learning Place </a>
    


          <li id="port"><a href="{% url 'forum:index' %}"> Forum </a></li>
          <li id="price"><a href="{% url 'main:developer' %}"> Developer </a></li>

          {% if user.is_authenticated %}
          <li><a href="#"><span class="glyphicon glyphicon-user"></span>Halo {{ request.user.username }}</a></li>
          <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
          {% else %}
          <li><a href="{% url 'account:signup' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
          <li><a href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
          {% endif %}


        </ul>
      </nav>

    </div>
  </header>
  <!-- End Header -->

      {% block content %}
      {% endblock %}  
 
       <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3> New Normal Info </h3>
          
                
                <p> Fakultas Ilmu Komputer <br>
                Kampus UI Depok, Pondok Cina, <br>
                Kecamatan Beji, Kota Depok, <br>
                Jawa Barat 16424 <br> <br>
             
                <strong>Phone:</strong> 
              
                (021)881646712
                <br>
                <strong>Email:</strong> 
              
                 new-normal-info@cs.ui.ac.id <br>
              </p>
              


        </div>
      </div>
      
          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:index' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'daftarrumahsakit:home' %}">RS</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'learningplace:index' %}">Learning Place</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'forum:index' %}">Forum</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:developer' %}">Developer</a></li>
            </ul>
          </div>

 
          <div class="col-lg-3 col-md-6" id="quotesyuk">
            <div class="footer-info">
              <h3> Quotes </h3>
          <p> Either you run the day </p>
          <p> or the day runs you </p>



          </div>
        </div>

</body>
</html>

templates/testimonialbyuserform.html
<!-- ======= Testimonial By User Section ======= -->
<section id="contact-form1" class="contact">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h3 style="color: black !important; width: 80% !important; margin: auto !important;">  Help us by sending your testimonials to make NewNormalInfo Website better!  </h3>
      </div>

      <div class="row">

        <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch" data-aos="fade-left">

             <div class="form-row">
              <div class="form-group col-md-6">
            
                <form id="testimonialform">
                  {% csrf_token %}
                  {{ form.as_p }}

                  <div class="center" style="margin-left: 220px !important; margin-bottom: -50px !important;">
                      <input class="btn-light round" id="test_button" type="submit" value="Send It Now">
                  </div>
              </form>
               
           
          </div>                          
          

        </div>
  

      </div>

    </div>
  </section><!-- End Testimonial By User Section -->