account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('signup/', views.signUp_view, name="signup"),
    path('logout/', views.logout_view, name="logout")
]

forum/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path('', views.index, name="index"),
    path('getposts', views.getPosts, name="getPosts"),
    path('view/<int:id>', views.view, name="view"),
    path('post/', views.post, name="post"),
    path('reply/<int:id>', views.reply, name="reply"),
    path('upvote/<int:id>', views.upvote, name="upvote"),
    path('downvote/<int:id>', views.downvote, name="downvote")
]

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, Subscribe, SaveSubscription, developer

app_name = "main"

urlpatterns = [
    path('', index, name="index"),
    path('subscribe/', Subscribe, name="subscribe"),
    path('subscribe/save/', SaveSubscription, name="save"),
    path('developer/', developer, name="developer")
]

newnormalinfo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('rumahsakit/', include('daftarrumahsakit.urls')),
    path('tempatbelajar/', include('learningplaceApp.urls')),
    #path('testimonial/', include('testimonialbyuserApp.urls')),
    path('forum/', include('forum.urls')),
    path('account/', include('account.urls'))
]

forum/models.py
from ckeditor.fields import RichTextField
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class PostNode(models.Model):
    content = RichTextField(null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    time_creation = models.DateTimeField(auto_now_add=True)
    hidden = models.BooleanField(default=False)

    def get_topic(self):
        postnode = self
        while (postnode.post != None):
            postnode = postnode.post
        return postnode.topic

    def update_topic(self):
        topic = self.get_topic()
        topic.replyCountUp()
        return topic

    def has_replies(self):
        return self.postnode_set.first() is not None

    @staticmethod
    def compare_datetime_with_now(datetime):
        time = timezone.now()

        if (datetime.year == time.year):
            if (datetime.month == time.month):
                if (datetime.day == time.day):
                    if (datetime.hour == time.hour):
                        if (datetime.minute == time.minute):
                            return str(time.second - datetime.second) + " detik lalu"
                        else:
                            return str(time.minute - datetime.minute) + " menit lalu"
                    else:
                        return str(time.hour - datetime.hour) + " jam lalu"
                else:
                    return str(time.day - datetime.day) + " hari lalu"
            else:
                return str(time.month - datetime.month) + " bulan lalu"
        else:
            return "{:02d}/{:02d}/{:04d}".format(datetime.day, datetime.month, datetime.year)

    def get_creation_datetime(self):
        return self.compare_datetime_with_now(self.time_creation)

class Topic(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    upvoters = models.ManyToManyField(User, related_name="upvoter")
    downvoters = models.ManyToManyField(User, related_name="downvoter")
    score = models.IntegerField(default=0)
    head = models.OneToOneField(PostNode, on_delete=models.CASCADE)
    recent_update = models.DateTimeField(auto_now_add=True)
    time_creation = models.DateTimeField(auto_now_add=True)
    reply_count = models.BigIntegerField(default=0)

    def replyCountUp(self):
        self.reply_count += 1
        self.recent_update = timezone.now()
        self.save()

    def updateScore(self):
        self.score = self.upvoters.all().count() - self.downvoters.all().count()
        self.save()

    def get_recent_datetime(self):
        return PostNode.compare_datetime_with_now(self.recent_update)

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title']

class PostNodeForm(forms.ModelForm):
    class Meta:
        model = PostNode
        fields = ['content']

forum/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.utils.html import escape

from .models import PostNode, PostNodeForm, Topic, TopicForm

def index(request, ordering="recent"):
    return render(request, "forum/index.html")

def getPosts(request):
    search = request.GET.get("search") or ""
    orderBy = request.GET.get("sort-by") or ""
    page = request.GET.get("p")
    # page argument check
    if (page == None or int(page) <= 0):
        if (orderBy != "popular" and orderBy != "recent"):
            return redirect(reverse("forum:getPosts")+"?sort-by=recent&p=1")
        else:
            return redirect(reverse("forum:getPosts")+"?sort-by="+orderBy+"&p=1")
    else:
        page = int(page)
    # orderBy argument check
    if (orderBy == "popular"):
        topics = Topic.objects.all().order_by("-score")
    elif (orderBy == "recent"):
        topics = Topic.objects.all().order_by("-recent_update")
    else: 
        return redirect(reverse("forum:getPosts")+"?sort-by=recent&p="+str(page))
    # Search query
    if (search != ""):
        topics = topics.filter(title__contains=search)
    # check if the page requested is available
    total_topics = len(topics)
    if (total_topics < (page-1)*10):
        page = total_topics // 10 + 1
        if (search != ""):
            return redirect(reverse("forum:getPosts")+"?sort-by="+orderBy+"&p="+str(page)+"&search="+search)
        else:
            return redirect(reverse("forum:getPosts")+"?sort-by="+orderBy+"&p="+str(page))
    else:
        topics = topics[(page-1)*10 : page*10]
    # Deserialization
    contentJson = dict()
    i = 0
    for topic in topics:
        post_pk = topic.pk
        post = {
            "title" : escape(topic.title),
            "recent_update" : topic.get_recent_datetime(),
            "reply_count" : topic.reply_count,
            "score" : str(topic.score),
            "post_pk" : str(post_pk)
        }
        if (topic.author != None):
            post["author"] = topic.author.username
        if (request.user.is_authenticated):
            if (request.user in topic.upvoters.all()):
                post["vote"] = "up"
            elif (request.user in topic.downvoters.all()):
                post["vote"] = "down"
            else:
                post["vote"] = "none"
        else:
            post["vote"] = "none"
        contentJson[i] = post
        i += 1

    responseJson = {
        "currPage" : str(page),
        "totalPages" : str((total_topics // 10) + 1),
        "content" : contentJson
    }

    return JsonResponse(responseJson)
    

def view(request, id):
    topic = Topic.objects.filter(pk=id).first()
    if (topic == None):
        return redirect(reverse("forum:index"))
    else:
        return render(request, "forum/view.html", {'topic' : topic})

@login_required
def post(request):
    if (request.method == "POST"):
        topicform = TopicForm(request.POST or None)
        postnodeform = PostNodeForm(request.POST or None)
        if (topicform.is_valid() and postnodeform.is_valid()):
            topic = topicform.save(commit=False)
            postnode = postnodeform.save(commit=False)
            postnode.hidden = False
            postnode.author = request.user
            postnode.save()
            topic.head = postnode
            topic.author = request.user
            topic.save()
            return redirect(reverse('forum:index'))
        else:
            return render(request, 'forum/post.html', {'topicform' : topicform, 'postnodeform' : postnodeform})
    else:
        topicform = TopicForm()
        postnodeform = PostNodeForm()
    return render(request, 'forum/post.html', {'topicform' : topicform, 'postnodeform' : postnodeform})

@login_required
def reply(request, id):
    postnodedest = PostNode.objects.filter(pk=id).first()
    if (postnodedest == None):
        return redirect(reverse("forum:index"))
    temp = postnodedest
    if (request.method == "POST"):
        postnodeform = PostNodeForm(request.POST or None)
        if (postnodeform.is_valid()):
            postnode = postnodeform.save(commit=False)
            postnode.post = postnodedest
            postnode.author = request.user
            postnode.hidden = False
            postnode.save()
            return redirect(reverse("forum:view", args=[postnode.update_topic().pk]))
        else:
            return render(request, "forum/reply.html", {"postnodeform" : postnodeform, "postnodedest" : postnodedest})
    else:
        postnodeform = PostNodeForm()
        return render(request, "forum/reply.html", {"postnodeform" : postnodeform, "postnodedest" : postnodedest})

def upvote(request, id):
    if (not request.user.is_authenticated):
        return HttpResponseForbidden('{"error" : "login required!"}')
    else:
        if (request.method == "POST"):
            topic = get_object_or_404(Topic, pk=id)
            if (request.user in topic.downvoters.all()):
                return HttpResponseBadRequest('{"error" : "user already have downvoted"}')
            elif (request.user in topic.upvoters.all()):
                topic.upvoters.remove(request.user)
                topic.updateScore()
                return JsonResponse({'status' : 'upvote canceled'})
            else:
                topic.upvoters.add(request.user)
                topic.updateScore()
                return JsonResponse({'status' : 'upvoted'})
        else:
            return HttpResponseForbidden('{"error" : "Invalid request type!"}')

def downvote(request, id):
    if (not request.user.is_authenticated):
        return HttpResponseForbidden('{"error" : "login required!"}')
    else:
        if (request.method == "POST"):
            topic = get_object_or_404(Topic, pk=id)
            if (request.user in topic.upvoters.all()):
                return HttpResponseBadRequest('{"error" : "user already have upvoted"}')
            elif (request.user in topic.downvoters.all()):
                topic.downvoters.remove(request.user)
                topic.updateScore()
                return JsonResponse({'status' : 'downvote canceled'})
            else:
                topic.downvoters.add(request.user)
                topic.updateScore()
                return JsonResponse({'status' : 'downvoted'})
        else:
            return HttpResponseForbidden('{"error" : "Invalid request type!"}')

templates/forum/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
<style>
.row {
    margin: 10px 0px 10px 0px;
}

p {
    vertical-align: middle;
}
#loader {
    width: 50px;
    height: 50px;
    margin: auto;
    display: block;
}

.vote {
    display: inline-block;
    overflow: hidden;
    width: 40px;
    height: 25px;
    cursor: pointer;
    background: url('/static/img/forum/votesprite.png');
    background-position: 0 -25px;
}

.score {
    text-align: center; 
    width: 40px; 
    height: 25px;
}

.vote.on {
    background-position: 0 2px;
}

.modified {
    color: orange;
}

.downvote {
    transform: rotate(180deg);
}
</style>
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>Forum</h1>
    {% if user.is_authenticated %}
    Anda masuk sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a>
    {% else %}
    Silakan login atau daftar untuk post topik dan komentar
    {% endif %}
    <div class="row d-flex justify-content-between form-inline">
        <div class="btn-group" role="group">
            <a id="recent" class="btn btn-primary">Terbaru</a>
            <a id="popular" class="btn btn-primary">Populer</a>
        </div>
        <input type="text" class="col-sm form-control" placeholder="Search" id="search">
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'forum:post' %}">Post Topik</a>
        {% else %}
        <div role="group" aria-label="Basic example">
            <a class="btn btn-primary" href="{% url 'account:login' %}">Login</a>
            <a class="btn btn-primary" href="{% url 'account:signup' %}">Daftar</a>
        </div>
        {% endif %}
    </div>
<script>
var sortBy = "recent";
var page = 1;
var totalPages = 0;

function  loadPosts() {
    $("#ForumPosts").empty();
    $("#loader").show();
    var search = $("#search").val();

    if (sortBy !== "recent" && sortBy !== "popular") sortBy = "recent";
    $.ajax({
        url: "{% url 'forum:getPosts' %}?sort-by=" + sortBy + "&p=" + parseInt(page) + "&search=" + search,
        type: "GET",
        dataType: "json",
        success: function(result) {
            resultHTML = "";
            $.each(result.content, function(key, val) {
                resultHTML += "<li class='list-group-item'><div class='row d-flex justify-content-between'>";
                resultHTML += "<div class='col'><div class='upvote vote ";
                if (val.vote === "up") resultHTML += "on";
                resultHTML += "' pk='" + val.post_pk + "'></div><div>";
                resultHTML += "<div class='score ";
                if (val.vote !== "none") resultHTML += "modified";
                resultHTML += "'>" + val.score + "</div>";
                resultHTML += "</div><div class='downvote vote ";
                if (val.vote === "down") resultHTML += "on";
                resultHTML += "' pk='"+ val.post_pk + "'></div></div>";
                resultHTML += "<div class='col-3'>";
                resultHTML += "<a href='view/" + val.post_pk + "'>" + val.title + "</a>";
                if ("author" in val)
                    resultHTML += "<div>Oleh: " + val.author + "</div></div><div class='col-2'>";
                else
                    resultHTML += "<div>Oleh: Anonim </div></div><div class='col-2'>";
                resultHTML += "Balasan: " + val.reply_count + "</div><div class='col-6'>Balasan terakhir: " + val.recent_update + "</div>";
                resultHTML += "</div></li>";
            });
            $("#loader").hide();
            $("#ForumPosts").html(resultHTML);
            $("#pagenum").html("Page " + result.currPage + " of " + result.totalPages)
            
            page = parseInt(result.currPage);
            totalPages = parseInt(result.totalPages);

            if (page === 1) {
                $("#first, #prev").hide();
            } else {
                $("#first, #prev").show();
            }

            if (page === totalPages) {
                $("#last, #next").hide();
            } else {
                $("#last, #next").show();
            }

            refreshHandlers();
        }
    });
}

function refreshHandlers() {
    $("#first").on("click", function() {
        if (page === 1) return;
        else page = 1;
        loadPosts();
    });

    $("#prev").on("click", function() {
        if (page === 1) return;
        else page -= 1;
        loadPosts();
    });

    $("#next").on("click", function() {
        if (page == totalPages) return;
        else page += 1;
        loadPosts();
    });

    $("#last").on("click", function() {
        if (page == totalPages) return;
        else page = totalPages;
        loadPosts();
    });

    $(".upvote").on("click", function(){
        var self = $(this);
        var csrftoken = Cookies.get('csrftoken');
        pk = self.attr("pk");
        $.ajax({
            url : "upvote/" + pk,
            type: "post",
            dataType: "json",
            headers: {'X-CSRFToken': csrftoken}, 
            success: function(result) {
                if (result.status === "upvoted" && !self.hasClass("on")) {
                    self.addClass("on");
                    var score = parseInt(self.next().text())+1;
                    self.next().html(score.toString());
                    self.next().addClass("score modified");
                } else if (result.status === "upvote canceled" && self.hasClass("on")) {
                    self.removeClass("on");
                    var score = parseInt(self.next().text())-1;
                    self.next().html(score.toString());
                    self.next().removeClass("modified").addClass("score");
                }
            }
        });
    });

    $(".downvote").on("click", function(){
        var self = $(this);
        var csrftoken = Cookies.get('csrftoken');
        pk = self.attr("pk");
        $.ajax({
            url : "downvote/" + pk,
            type: "post",
            dataType: "json",
            headers: {'X-CSRFToken': csrftoken},
            success: function(result) {
                if (result.status === "downvoted" && !self.hasClass("on")) {
                    self.addClass("on");
                    var score = parseInt(self.prev().text())-1;
                    self.prev().html(score.toString());
                    self.prev().addClass("score modified");
                } else if (result.status === "downvote canceled" && self.hasClass("on")) {
                    self.removeClass("on");
                    var score = parseInt(self.prev().text())+1;
                    self.prev().html(score.toString());
                    self.prev().removeClass("modified").addClass("score");
                }
            }
        });
    });
}

$(document).ready(function() {
    loadPosts();

    $("#recent").on("click", function() {
        sortBy = "recent";
        loadPosts();
    });

    $("#popular").on("click", function() {
        sortBy = "popular";
        loadPosts();
    });

    $("#search").on("keyup", function() {
        page = 1;
        totalPages = 0;
        loadPosts();
    });
});
</script>
    <div class="spinner-border" id="loader"></div>
    <ul class="list-group" id="ForumPosts">
    </ul>
    <div class="row justify-content-center">
        <nav>
            <ul class="pagination">
            <li class="page-item"><a class="page-link" id="first">&lt;&lt;</a></li>
            <li class="page-item"><a class="page-link" id="prev">&lt;</a></li>
            <li class="page-item"><a class="page-link" id="pagenum"></a></li>
            <li class="page-item"><a class="page-link" id="next">&gt;</a></li>
            <li class="page-item"><a class="page-link" id="last">&gt;&gt;</a></li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

templates/forum/post.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | Post Topic{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
{% load bootstrap4 %}
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>Post Topic</h1>
    <p>Post sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a></p>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form topicform %}
        {{ postnodeform.media }}
        {{ postnodeform.as_p }}
        <input class="btn btn-primary" type="submit" value="Post">
        <a class="btn btn-primary" href="{% url 'forum:index' %}">Kembali</a>
    </form>
</div>
{% endblock %}

templates/forum/posttemplate.html
{% if postnode.hidden %}
Post ini telah dihapus
{% else %}
<div id="postcontent">
    <b>{% if postnode.author %}{{ postnode.author }}{% else %}Anonim{% endif %}</b> - {{ postnode.get_creation_datetime }}
    <div>{{ postnode.content|safe }}</div>
</div>
{% endif %}
<a href="{% url 'forum:reply' postnode.pk %}">Balas</a>
{% if postnode.has_replies %}
    <ul id="reply">
        {% for childnode in postnode.postnode_set.all %}
            <li id="reply">{% include "forum/posttemplate.html" with postnode=childnode %}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/forum/reply.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | Balas{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
{% endblock %}
{% block content %}
{% load bootstrap4 %}
<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px;">
    <h1>Balas</h1>
    <div class="card">
        <div class="card-body">
            <p class="card-text">
                <b>{% if postnodedest.author %}{{ postnodedest.author }}{% else %}Anonim{% endif %}</b> - {{ postnodedest.get_creation_datetime }} <br>
                {{ postnodedest.content|safe }}
            </p>
        </div>
    </div>
    <br>
    <div>Balas sebagai {{ user.username }} <a href="{% url 'account:logout' %}">logout</a></div>
    <form method="POST" style="margin-top: 20px;">
        {% csrf_token %}
        {{ postnodeform.media }}
        {{ postnodeform.as_p }}
        <input class="btn btn-primary" type="submit" value="Balas">
    </form>
</div>
{% endblock %}

templates/forum/view.html
{% extends "base.html" %}
{% load static %}
{% block title %}Forum | {{ topic.title }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}" /> 
{% endblock %}
{% block content %}

<style>
#postbox li{
    list-style: none;
    margin: 10px 0px 10px 0px;
    padding-left: 10px;
}

#postbox {
    padding-inline-start: 10px;
}

#post ul{
    border-left: 1px solid black;
    padding-inline-start: 1%;
}
#postcontent ul{
    padding-inline-start: 40px;
    border-left: none;
}

#postcontent li{
    padding-left: 0px;
    margin: 0px;
    list-style: disc;
}

@media (max-width: 1000px) {
    #postbox {
        padding-inline-start: 0px;
    }

    #post ul{
        border-left: 0.5px solid black;
        padding-inline-start: 0.5%;
    }

}
</style>

<div class="container" style="max-width: 1000px; margin: auto; margin-top: 100px; margin-bottom: 100px;">
    <h1>{{ topic.title }}</h1>
    <p>{{ topic.time_creation }} <a href="{% url 'forum:index' %}">Kembali</a></p>
    <p>Pembuat : {% if topic.author %}{{ topic.author }}{% else %}Anonim{% endif %}</p>
    <ul id="postbox">
        <li id="post">
            {% include "forum/posttemplate.html" with postnode=topic.head %}
        </li>
    </ul>
    <a href="{% url 'forum:index' %}" class="btn btn-primary" style="margin-top: 5px">Kembali</a>
</div>
{% endblock %}